groups:
- name: info
  rules:
  - alert: HighMemoryUsageInfo
    expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes * 100 >= 50
    for: 5m
    labels:
      service: MemoryUsage
      severity: info
    annotations:
      summary: "High memory usage on {{ $labels.mountpoint }}"
      description: "Memory usage on the instance `{{ $labels.instance }}` has been above 50% for more than 5 minutes. Current memory usage: `{{ $value }}%`."

  - alert: FilesystemReadOnlyInfo
    expr: node_filesystem_readonly{fstype=~"ext4|xfs"} == 1
    for: 5m
    labels:
      service: Filesystem
      severity: info
    annotations:
      summary: "Filesystem read-only on {{ $labels.instance }}"
      description: "The filesystem on the instance `{{ $labels.instance }}` is currently in read-only mode."

  - alert: HighSwapUsageInfo
    expr: (((node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes)/node_memory_SwapTotal_bytes)*100) > 50
    for: 10m
    labels:
      service: SwapUsage
      severity: info
    annotations:
      summary: "High swap usage on {{ $labels.instance }}"
      description: "Swap usage on the instance `{{ $labels.instance }}` is high. Current swap usage: `{{ $value }}%`."

  - alert: HighIOWaitTimeInfo
    expr: avg by(instance) (rate(node_cpu_seconds_total{mode="iowait"}[5m])) * 100 > 20
    for: 15m
    labels:
      service: IO
      severity: info
    annotations:
      summary: "High I/O wait time on {{ $labels.instance }}"
      description: "I/O wait time on the instance `{{ $labels.instance }}` is high. Current I/O wait time: `{{ $value }}%`."

  - alert: NetworkLatencyInfo
    expr: avg_over_time(node_network_receive_errs_total[10m]) > 0
    for: 10m
    labels:
      service: Network
      severity: info
    annotations:
      summary: "Network latency on {{ $labels.instance }}"
      description: "Network latency has been detected on the instance `{{ $labels.instance }}`. There were errors in the last 10 minutes."

  - alert: HighCPUUsageInfo
    expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 50
    for: 10m
    labels:
      service: CPUUsage
      severity: info
    annotations:
      summary: "High CPU usage on {{ $labels.instance }}"
      description: "CPU usage on the instance `{{ $labels.instance }}` is high. Current CPU usage: `{{ $value }}%`."

  - alert: SystemRebootInfo
    expr: node_boot_time_seconds > time() - 600
    for: 10m
    labels:
      service: SystemUptime
      severity: info
    annotations:
      summary: "System reboot on {{ $labels.instance }}"
      description: "The system on the instance `{{ $labels.instance }}` was rebooted within the last 10 minutes."

  - alert: HighFileDescriptorUsageInfo
    expr: (node_filefd_allocated{job="node"} / node_filefd_maximum{job="node"}) * 100 > 70
    for: 5m
    labels:
      service: FileDescriptors
      severity: info
    annotations:
      summary: "High file descriptor usage on {{ $labels.instance }}"
      description: "File descriptor usage on the instance `{{ $labels.instance }}` is high. Current usage: `{{ $value }}%`."

- name: info_alerts
  rules:
  - alert: HostEdacCorrectableErrorsDetected
    expr: '(increase(node_edac_correctable_errors_total[1m]) > 0) * on(instance) group_left (nodename) node_uname_info{nodename=~".+"}'
    for: 0m
    labels:
      severity: info
    annotations:
      summary: "Host EDAC Correctable Errors detected (instance {{ $labels.instance }})"
      description: "Host `{{ $labels.instance }}` has had `{{ printf \"%.0f\" $value }}` correctable memory errors reported by EDAC in the last 1 minute."

  - alert: HostMemoryIsUnderUtilized
    expr: '(100 - (rate(node_memory_MemAvailable_bytes[30m]) / node_memory_MemTotal_bytes * 100) < 20) * on(instance) group_left (nodename) node_uname_info{nodename=~".+"}'
    for: 1w
    labels:
      severity: info
    annotations:
      summary: "Host Memory is underutilized (instance {{ $labels.instance }})"
      description: "Memory on the instance `{{ $labels.instance }}` has been underutilized (< 20%) for the past 1 week."
